### PR TITLE
Added rand function

### PR DESCRIPTION
**Pull request by antonioperic**

### CODE REVIEW

**Comment by luxifer** [comment]
please could you fix this PR? http://drone.luxiferapp.com/github.com/luxifer/doctrine-functions/commit/1226fa165b8d3bc3d687e241a9aebc91c272a332?branch=rand
I know it's one of my doctrine mockup class but i think it could be easy to fix.

Thanks in advance

**Comment by antonioperic** [comment]
@luxifer Hi, i will check it later today

**Comment by antonioperic** [comment]
@luxifer lets wait for tests but i think it should be good now

**Comment by antonioperic** [comment]
@luxifer  all green :)

**Comment by luxifer** [comment]
Thanks, there's also a typo in the folder name `MIsc` instead of `Misc`. But this is a numeric function as it returns a number so can you make the change of the folder and the namespace to `Numeric`

**Comment by antonioperic** [comment]
Done

**Pull request merged**
